export const PRODUCT_TYPES = {
    FETCHING_START: "product/FETCHING_START",
    UPDATE_PRODUCT: "product/UPDATE_PRODUCT",
    UPDATE_DIRECTRY: "product/UPDATE_DIRECTRY",
    FETCHING_FAILED: "product/FETCHING_FAILED"
}